name: vrchat_dart
description: This is a Dart client that interacts with the unofficial VRChat API
homepage: https://github.com/vrchatapi/vrchatapi-dart
version: 3.2.2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  vrchat_dart_generated: ^1.11.1
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  dio: ^5.0.0
  web_socket_channel: ^2.1.0
  json_annotation: ^4.7.0
  built_value: ^8.1.1
  collection: ^1.15.0
  dio_response_validator: ^0.2.1

dev_dependencies:
  rexios_lints: ^5.0.0
  build_runner: ^2.0.6
  json_serializable: ^6.0.1
  yaml: ^3.1.1
  parselyzer: ^0.1.0
