name: vrchat_dart_example
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  vrchat_dart:
    path: ../

  otp: ^3.1.3

dev_dependencies:
  rexios_lints: ^5.0.0

dependency_overrides:
  vrchat_dart_generated:
    path: ../../vrchat_dart_generated
  # TODO: REMOVE
  web_socket_channel:
    git:
      url: https://github.com/Rexios80/web_socket_channel.git
      ref: eb1e3769d1d918b7df32705372022ad6a123745e
